scummvm: Fix build with upcoming fluidsynth 2.2.0
fluidsynth 2.2.0 introduced API changes causing:

| audio/softsynth/fluidsynth.cpp:256:11: error: invalid conversion from 'long int (*)(void*)' to 'fluid_sfloader_callback_tell_t' {aka 'long long int (*)(void

The change should be compatible for version < 2.2.0 either

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>