Add pingus version 0.7.6
This commit was made by using and modifying the pingus recipe
  comming from oe-classic at the following revision:
  07069799d5e9688e24b4dc2d5253aea2e96dd4a7

The version.patch is for errors like:
  error: unable to find string literal operator 'operator"" VERSION'

Pingus was tested on the om-gta04 machine
  (from meta-smartphone/meta-openmoko) with the following command line:
  pingus -d /usr/share/pingus/data/ --no-auto-scrolling -m -f -R 480x640
  And with a bluetooth keyboard because the screen was too small to
  display the button used to enter a map.

The .desktop file is generic tough.

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>